# List of controller 
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot_controller:
      type: Custom_Franka_Controller/HybridFTController

    # task_space_controller:
    #   type: Task_Space_Controller/TaskSpaceController
      
      type: Custom_Franka_Controller/HybridFTController
      # gazebo_practise - package name where the plugin is defined
      # CustomRobotController - self defined C++ class name inside the controller program

    # franka_arm_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController


    # franka_hand_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController
    
    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    

# Controller parameter
# Custom controller
robot_controller:
  ros__parameters:
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7

    command_interfaces:
      # - position 
      - velocity

    state_interfaces:
      - position
      - velocity

joint_trajectory_controller:
  ros__parameters:
    gazebo: true
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
  
    command_interfaces:
      - position 
      - velocity
    state_interfaces:
      - position
      - velocity

# Controller from Moveit setup assistant
# franka_arm_controller:
#   ros__parameters:
#     joints:
#       - fr3_joint1
#       - fr3_joint2
#       - fr3_joint3
#       - fr3_joint4
#       - fr3_joint5
#       - fr3_joint6
#       - fr3_joint7
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
# franka_hand_controller:
#   ros__parameters:
#     joints:
#       - fr3_finger_joint1
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: force_torque_sensor
    frame_id: fr3_link7
    topic_name: /force_torque
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z



# joint_position_example_controller:
#   ros__parameters:
#     gazebo: true

# joint_velocity_example_controller:
#   ros__parameters:
#     gazebo: true
  
# joint_impedance_example_controller:
#   ros__parameters:
#     k_gains:
#       - 24.0
#       - 24.0
#       - 24.0
#       - 24.0
#       - 10.0
#       - 6.0
#       - 2.0
#     d_gains:
#       - 2.0
#       - 2.0
#       - 2.0
#       - 1.0
#       - 1.0
#       - 1.0
#       - 0.5